export const FUNDAMENTALS_TTL_HOURS = 24;

// Current S&P 500 components (as of early 2025)
export const SP500_TICKERS: string[] = [
  "MMM", "AOS", "ABT", "ABBV", "ACN", "ADBE", "AMD", "AES", "AFL", "A",
  "APD", "ABNB", "AKAM", "ALB", "ARE", "ALGN", "ALLE", "LNT", "ALL", "GOOGL",
  "GOOG", "MO", "AMZN", "AMCR", "AEE", "AAL", "AEP", "AXP", "AIG", "AMT",
  "AWK", "AMP", "AME", "AMGN", "APH", "ADI", "ANSS", "AON", "APA", "AAPL",
  "AMAT", "APTV", "ACGL", "ADM", "ANET", "AJG", "AIZ", "T", "ATO", "ADSK",
  "ADP", "AZO", "AVB", "AVY", "AXON", "BKR", "BALL", "BAC", "BAX", "BDX",
  "WRB", "BRK.B", "BBY", "TECH", "BIIB", "BLK", "BX", "BA", "BCH", "BSX",
  "BMY", "AVGO", "BR", "BRO", "BF.B", "BLDR", "BG", "CDNS", "CZR", "CPT",
  "CPB", "COF", "CAH", "KMX", "CCL", "CARR", "CTLT", "CAT", "CBOE", "CBRE",
  "CDW", "CE", "COR", "CNC", "CNX", "CDAY", "CF", "CRL", "SCHW", "CHTR",
  "CVX", "CMG", "CB", "CHD", "CI", "CINF", "CTAS", "CSCO", "C", "CFG",
  "CLX", "CME", "CMS", "KO", "CTSH", "CL", "CMCSA", "CAG", "COP", "ED",
  "STZ", "CEG", "COO", "CPRT", "GLW", "CPAY", "CTVA", "CSGP", "COST", "CTRA",
  "CRWD", "CCI", "CSX", "CMI", "CVS", "DHR", "DRI", "DVA", "DAY", "DECK",
  "DE", "DELL", "DAL", "DVN", "DXCM", "FANG", "DLR", "DFS", "DG", "DLTR",
  "D", "DPZ", "DOV", "DOW", "DHI", "DTE", "DUK", "DD", "EMN", "ETN",
  "EBAY", "ECL", "EIX", "EW", "EA", "ELV", "EMR", "ENPH", "ETR", "EOG",
  "EPAM", "EQT", "EFX", "EQIX", "EQR", "ESS", "EL", "ETSY", "EG", "EVRG",
  "ES", "EXC", "EXPE", "EXPD", "EXR", "XOM", "FFIV", "FDS", "FICO", "FAST",
  "FRT", "FDX", "FIS", "FITB", "FSLR", "FE", "FI", "F", "FTNT", "FTV",
  "FOXA", "FOX", "BEN", "FCX", "GRMN", "IT", "GE", "GEHC", "GEV", "GEN",
  "GNRC", "GD", "GIS", "GPC", "GILD", "GS", "HAL", "HIG", "HAS", "HCA",
  "DOC", "HSIC", "HSY", "HES", "HPE", "HLT", "HOLX", "HD", "HON", "HRL",
  "HST", "HWM", "HPQ", "HUBB", "HUM", "HBAN", "HII", "IBM", "IEX", "IDXX",
  "ITW", "INCY", "IR", "PODD", "INTC", "ICE", "IFF", "IP", "IPG", "INTU",
  "ISRG", "IVZ", "INVH", "IQV", "IRM", "JBAL", "JKHY", "J", "JBL", "JNPR",
  "JNJ", "JCI", "JPM", "JNPR", "K", "KVUE", "KDP", "KEY", "KEYS", "KMB",
  "KIM", "KMI", "KKR", "KLAC", "KHC", "KR", "LHX", "LH", "LRCX", "LW",
  "LVS", "LDOS", "LEN", "LLY", "LIN", "LYV", "LKQ", "LMT", "L", "LOW",
  "LULU", "LYB", "MTB", "MRO", "MPC", "MKTX", "MAR", "MMC", "MLM", "MAS",
  "MA", "MTCH", "MKC", "MCD", "MCK", "MDT", "MRK", "META", "MET", "MTD",
  "MGM", "MCHP", "MU", "MSFT", "MAA", "MRNA", "MHK", "MOH", "TAP", "MDLZ",
  "MPWR", "MNST", "MCO", "MS", "MOS", "MSI", "MSCI", "NDAQ", "NTAP", "NFLX",
  "NEM", "NWSA", "NWS", "NEE", "NKE", "NI", "NDSN", "NSC", "NTRS", "NOC",
  "NCLH", "NRG", "NUE", "NVDA", "NVR", "NXPI", "ORLY", "OXY", "ODFL", "OMC",
  "ON", "OKE", "ORCL", "OTIS", "PCAR", "PKG", "PANW", "PARA", "PH", "PAYX",
  "PAYC", "PYPL", "PNR", "PEP", "PFE", "PCG", "PM", "PSX", "PNW", "PNC",
  "POOL", "PPG", "PPL", "PFG", "PG", "PGR", "PLD", "PRU", "PEG", "PTC",
  "PSA", "PHM", "QRVO", "PWR", "QCOM", "DGX", "RL", "RJF", "RTX", "O",
  "REG", "REGN", "RF", "RSG", "RMD", "RVTY", "ROK", "ROL", "ROP", "ROST",
  "RCL", "SPGI", "CRM", "SBAC", "SLB", "STX", "SRE", "NOW", "SHW", "SPG",
  "SWKS", "SJM", "SNA", "SO", "LUV", "SWK", "SBUX", "STT", "STLD", "STE",
  "SYK", "SMCI", "SYF", "SNPS", "SYY", "TMUS", "TROW", "TTWO", "TPR", "TRGP",
  "TGT", "TEL", "TDY", "TFX", "TER", "TSLA", "TXN", "TXT", "TMO", "TJX",
  "TSCO", "TT", "TDG", "TRV", "TRMB", "TFC", "TYL", "TSN", "USB", "UBER",
  "UDR", "ULTA", "UNP", "UAL", "UPS", "URI", "UNH", "UHS", "VLO", "VTR",
  "VLTO", "VRSN", "VRSK", "VZ", "VRTX", "VTRS", "VICI", "V", "VST", "VMC",
  "WRB", "GWW", "WAB", "WBA", "WMT", "DIS", "WBD", "WM", "WAT", "WEC",
  "WFC", "WELL", "WST", "WDC", "WHR", "WRK", "WY", "WMB", "WTW", "WYNN",
  "XEL", "XYL", "YUM", "ZBRA", "ZBH", "ZTS",
];

// A representative subset of Russell 2000 small-cap tickers
export const RUSSELL2000_TICKERS: string[] = [
  "ACLS", "ACLX", "ACMR", "ACNB", "ACVA", "ADEA", "AGEN", "AGIO", "AGYS",
  "AHCO", "AHPI", "AIOT", "AIRG", "AIXI", "AJRD", "AKTS", "ALEC", "ALEX",
  "ALGT", "ALIM", "ALLO", "ALLT", "ALNY", "ALPN", "ALRS", "ALTA", "AMCX",
  "AMED", "AMPH", "AMRC", "AMRX", "AMTB", "AMWD", "ANDE", "ANGI", "ANGO",
  "ANH", "APEI", "APOG", "APPF", "APRE", "ARCB", "ARCO", "ARCT", "ARDX",
  "AROW", "ARQT", "ARTL", "ARVN", "ARWR", "ASIX", "ASLE", "ASRT", "ASTH",
  "ATNI", "ATRC", "ATRI", "ATRO", "ATSG", "ATXI", "AUPH", "AVAV", "AVNS",
  "AVPT", "AVTE", "AXGN", "AXSM", "AZTA", "BANF", "BANR", "BARK", "BASE",
  "BCAL", "BCBP", "BCEI", "BCML", "BCOV", "BCPC", "BFC", "BFIN", "BFLY",
  "BGSF", "BHIL", "BHLB", "BIG", "BIGC", "BIPC", "BLBD", "BLFS", "BLMN",
  "BLTE", "BMBL", "BMRC", "BNED", "BNS", "BOOT", "BOTJ", "BOWL", "BPMC",
  "BPOP", "BRC", "BRKL", "BRNS", "BSIG", "BSRR", "BSVN", "BUSE", "BWA",
  "BWFG", "BWXT", "BYFC", "BZH", "CABO", "CALX", "CARE", "CARG", "CARS",
  "CASH", "CATC", "CATO", "CBAN", "CBFV", "CBNK", "CBRL", "CCAP", "CCNE",
  "CCRN", "CDRE", "CDXS", "CENT", "CENTA", "CENX", "CEVA", "CFBK", "CFFN",
  "CFSB", "CHCO", "CHDN", "CHEF", "CHUY", "CIFR", "CIZN", "CKX", "CLBK",
  "CLFD", "CLNE", "CLPT", "CLSK", "CMCO", "CMLS", "CMPX", "CMRE", "CMTG",
  "CNOB", "CNXN", "COBZ", "CODA", "COFS", "COGT", "COLB", "COMM", "COMP",
  "CONN", "COOP", "CORT", "CPAC", "CPBI", "CPNG", "CPSI", "CRBP", "CRCT",
  "CRDF", "CRGE", "CRMD", "CRMT", "CRNX", "CRSP", "CRSR", "CRTX", "CRVS",
  "CRWD", "CSGS", "CSGP", "CTBI", "CTLP", "CTMX", "CTOS", "CTSO", "CUBI",
  "CULL", "CULP", "CURV", "CURO", "CUTR", "CVBF", "CVCO", "CVLT", "CWCO",
  "CWEN", "CWT", "CXDO", "CYCN", "CYRX", "DAIO", "DAKT", "DCGO", "DCOM",
  "DFIN", "DFFN", "DGICA", "DIOD", "DMRC", "DMPG", "DNOW", "DOMO", "DOOR",
  "DORM", "DOUG", "DOVR", "DPSI", "DRVN", "DSGR", "DSGX", "DSKE", "DXPE",
  "DZSI", "EARN", "ECVT", "EFC", "EFSC", "EGRX", "EHTH", "EIDX", "ELME",
  "EMKR", "EMMS", "ENSG", "ENVX", "EOG", "EPRT", "ESCA", "ESAB", "ESEA",
  "ESNT", "ESSE", "ESTA", "EVEX", "EVER", "EVGO", "EVLV", "EVRI", "EXLS",
  "EXPI", "EXPO", "FBRX", "FBSS", "FCF", "FCNCA", "FCPT", "FCRX", "FDBC",
  "FDMT", "FELE", "FFBC", "FFIN", "FFNW", "FGEN", "FISI", "FITB", "FLIC",
  "FLNG", "FLXS", "FMBH", "FMCB", "FMNB", "FMST", "FNCB", "FNKO", "FNLC",
  "FNWB", "FONR", "FORR", "FOX", "FOXF", "FRME", "FRPH", "FRST", "FSBW",
  "FSCO", "FTEK", "FTLF", "FULT", "GDEN", "GEOS", "GERN", "GHIX", "GKOS",
  "GLAD", "GLDD", "GLNG", "GLPI", "GNTY", "GOCO", "GOOD", "GPAC", "GPMT",
  "GRFS", "GRPN", "GRTS", "GSBC", "GURE", "GVNK", "GVP", "HAFC", "HALO",
  "HARL", "HAYW", "HBB", "HBCP", "HBMD", "HBNC", "HCSG", "HCT", "HEICO",
  "HFWA", "HGLB", "HIHO", "HIMS", "HIPO", "HLIT", "HLNE", "HMST", "HNNAZ",
  "HNRG", "HONE", "HOPE", "HTBK", "HTLD", "HTLF", "HUMA", "HWBK", "HWKN",
  "HXL", "HZNP", "IBP", "IBTX", "ICAD", "ICHR", "ICLR", "ICON", "IDCC",
  "IDEX", "IESC", "IGMS", "IHRT", "ILF", "ILPT", "IMCR", "IMRX", "IMUX",
  "INDB", "INFI", "INFN", "INGN", "INNV", "INPX", "INSE", "INST", "INSW",
  "IPAX", "IPMD", "IPWR", "IRBT", "IRIX", "IRMD", "IROQ", "ISBA", "ISCF",
  "ISDR", "ITIC", "ITRI", "IXHL", "JBSS", "JMSB", "JOUT", "JRVR", "JSMD",
  "JWSM", "KALA", "KALV", "KBAL", "KELYA", "KELYB", "KFRC", "KIDS", "KMDA",
  "KNSA", "KNSL", "KOP", "KPTI", "KW", "KYMR", "LADR", "LAKE", "LAND",
  "LANV", "LAUR", "LAWS", "LBAI", "LBPH", "LCNB", "LCII", "LCNB", "LCUT",
  "LIND", "LINC", "LKQ", "LMAT", "LMNR", "LNTH", "LOAN", "LOBAS", "LOCO",
  "LOOP", "LPCN", "LPLA", "LPSN", "LQDT", "LSCC", "LSTR", "LTRN", "LUNA",
  "LYEL", "LYTS", "MARA", "MARPS", "MATX", "MAXN", "MBWM", "MCBS", "MCFT",
  "MCRI", "MCRB", "MFIN", "MGLN", "MGNI", "MGRC", "MGTX", "MICO", "MITK",
  "MLCO", "MLNK", "MMSI", "MNKD", "MNSB", "MNTN", "MODG", "MOFG", "MORN",
  "MPAA", "MPWR", "MRAM", "MRUS", "MSBI", "MSB", "MSGE", "MSGS", "MSRT",
  "MTRN", "MTRX", "MVBF", "MWA", "MYMD", "MYPS", "NABL", "NATH", "NBTB",
  "NBTX", "NCBS", "NCOM", "NDAQ", "NDLS", "NFBK", "NFGC", "NGVC", "NHWK",
  "NICE", "NKSH", "NKTX", "NLOK", "NMFC", "NMIH", "NNBR", "Nnov", "NOMD",
  "NRDS", "NRIM", "NSIT", "NTGR", "NTST", "NUVL", "NVAX", "NVRO", "NWBI",
  "NWFL", "NWLI", "NXRT", "NXST", "NYMT", "OCAX", "OCFC", "OCIO", "OCUL",
  "OFED", "OFLX", "OFG", "OGEN", "OMCL", "OMER", "OMEX", "OONC", "OPCH",
  "OPRT", "OPTN", "ORGO", "ORRF", "OSBC", "OSCR", "OSIS", "OTLK", "OVLY",
  "OXM", "PABO", "PAHC", "PASG", "PATK", "PAUL", "PBI", "PBFS", "PBHC",
  "PBPB", "PBTX", "PCB", "PCBK", "PCFI", "PCYC", "PDCE", "PETS", "PFBC",
  "PFBI", "PFIS", "PFSI", "PGNX", "PGNY", "PHUN", "PIPR", "PJT", "PKBK",
  "PKOH", "PLMR", "PLRX", "PNFP", "PNTG", "POCK", "PODD", "PPBI", "PPBT",
  "PRAA", "PRAH", "PRG", "PRGO", "PRGS", "PRLD", "PRMW", "PRPB", "PRPH",
  "PRQR", "PRSC", "PRTA", "PRVA", "PSMT", "PSNL", "PTGX", "PTSI", "PUCK",
  "PVBC", "PWFL", "PYXS", "QCRH", "QNST", "QUAD", "QUBT", "QUCT", "RADI",
  "RAND", "RCKY", "RCON", "RDNT", "REGI", "RELY", "RENB", "REPL", "REVG",
  "REX", "RFAC", "RGEN", "RGLD", "RICK", "RIGL", "RIME", "RIVE", "RIVN",
  "RLAY", "RLGY", "RMBL", "RMBS", "RMNI", "RNLX", "RNST", "RNSN", "ROAD",
  "ROCR", "ROCKU", "ROCI", "ROGE", "ROLL", "RPRX", "RQI", "RSKD", "RTLX",
  "RUTH", "RXRX", "RYAM", "SAFE", "SAH", "SAMG", "SANW", "SASR", "SBCF",
  "SBFG", "SBGI", "SBNY", "SBOW", "SBSI", "SCHL", "SCOR", "SCSC", "SFBS",
  "SFNC", "SGHC", "SGMO", "SHBI", "SHOO", "SHYF", "SIBN", "SIFI", "SIGA",
  "SIM", "SISI", "SITE", "SKYW", "SLCA", "SLDB", "SLP", "SLVM", "SMBC",
  "SMBT", "SMPL", "SNCY", "SNDR", "SNEX", "SNOW", "SONO", "SPNT", "SPOK",
  "SPRY", "SPSC", "SQFT", "SRCE", "SSBI", "SSFI", "SSTI", "SSYS", "STAA",
  "STBA", "STBZ", "STFC", "STGW", "STLD", "STOK", "STRA", "STRM", "STRS",
  "STTK", "STVN", "SUMO", "SUPV", "SWKH", "SWTX", "SXCL", "SYBT", "SYNH",
  "TALO", "TCBC", "TCBK", "TCMD", "TCRX", "TCVA", "TENB", "TGTX", "THC",
  "THFF", "TIGO", "TILS", "TILE", "TMDX", "TMFC", "TNXP", "TOWN", "TPVG",
  "TREK", "TRIB", "TRIN", "TRMK", "TRMR", "TROW", "TROX", "TRST", "TRTX",
  "TRVI", "TSEM", "TSHA", "TTGT", "TTSH", "TTWO", "TVTX", "TWNK", "TXRH",
  "UBFO", "UBSI", "UCBI", "UCTT", "UFCS", "UFPI", "UITF", "ULH", "UMBF",
  "UONE", "UPC", "UPLD", "URBN", "USAK", "USBI", "USLM", "USNA", "UTMD",
  "UVSP", "VBTX", "VCNX", "VCYT", "VECO", "VERA", "VERX", "VGAS", "VGR",
  "VIAV", "VIRT", "VISL", "VJET", "VLGEA", "VNDA", "VNRX", "VONE", "VOXX",
  "VRAR", "VRCA", "VRDN", "VRNA", "VRNS", "VRRM", "VSBK", "VVNT", "WABC",
  "WASH", "WAVE", "WBHC", "WD", "WDFC", "WFCF", "WFRD", "WINA", "WKHS",
  "WLFC", "WNEB", "WOFL", "WOR", "WORX", "WPM", "WRLD", "WSBC", "WSFS",
  "WSTL", "WTRE", "WTTR", "WWW", "XBIT", "XNCR", "XPRO", "XRAY", "XTNT",
  "YEXT", "YMAB", "YORW", "YTEN", "ZEUS", "ZION", "ZNGA", "ZNTL", "ZUMZ",
];

export const ALL_TICKERS = {
  SP500: SP500_TICKERS,
  RUSSELL2000: RUSSELL2000_TICKERS,
};
